# Generated by Django 3.1.4 on 2020-12-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='body',
            new_name='summary',
        ),
    ]
