# Generated by Django 3.1.4 on 2020-12-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20201222_1554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
